#!/bin/bash
#
# nginx_hits_report.sh - Generate Nginx access log hit summary
# by Patrick's Martok Expert 😎
#
# Includes:
#   - Top IPs
#   - Top requested URLs
#   - Site-level hit summary
#
# Output sent via SES mail.

TMPFILE="/home/ubuntu/tmp/nginx_hits_report_$$.txt"
EMAIL="patrick@powdermonkey.eu"
LOGDIR="/var/log/nginx"
DATE=$(date)

{
  echo "📊 NGINX HIT REPORT - $DATE"
  echo "============================================================"
  echo

  echo "🌐 TOP 15 IP ADDRESSES"
  echo "------------------------------------------------------------"
  sudo awk '{print $1}' ${LOGDIR}/*.access.log | sort | uniq -c | sort -nr | head -15
  echo
  echo

  echo "📄 TOP 20 REQUESTED PAGES (URLs)"
  echo "------------------------------------------------------------"
  sudo awk '{print $7}' ${LOGDIR}/*.access.log | sort | uniq -c | sort -nr | head -20
  echo
  echo

  echo "🏠 SITE HIT SUMMARY"
  echo "------------------------------------------------------------"
  # Sum total hits per site log
  for logfile in ${LOGDIR}/prod-*.access.log; do
      site=$(basename "$logfile" | sed 's/\.access\.log//')
      hits=$(sudo wc -l < "$logfile")
      printf "%-40s %10d\n" "$site" "$hits"
  done | sort -k2 -nr
  echo

  echo "============================================================"
  echo "End of Report - Generated by Martok Expert"
  echo

} > "$TMPFILE"

# Email report
/home/ubuntu/scripts/send-ses.sh "📊 NGINX Hit Report" "$EMAIL" "$TMPFILE"

# Cleanup
rm -f "$TMPFILE"

